[configuration]
== Configuration

=== Integration to applications

==== Maven dependency

[line-through]#Please add following to pom.xml to introduce Spring Security WebAuthn and its dependencies.#
For now, it is not published to Maven Central as it requires Spring Security custom build.

[source, xml]
----
<dependency>
	<groupId>net.sharplab.springframework.security.extensions</groupId>
	<artifactId>spring-security-webauthn-core</artifactId>
	<version>${version}</version>
</dependency>
----

==== Java Config

===== Integrating WebAuthnProcessingFilter

`WebAuthnProcessingFilter`, which listens WebAuthn authentication requests can be configured with JavaConfig.
Please define a configuration class, make it inherit `WebSecurityConfigurerAdapter`, apply `WebAuthnLoginConfigurer`
in a method overrides `configure(HttpSecurity http)`.
`WebAuthnLoginConfigurer` has a factory method named `webAuthnLogin()`, which can be utilized.

```java

import static net.sharplab.springframework.security.webauthn.config.configurers.WebAuthnLoginConfigurer.webAuthnLogin;

public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        // WebAuthn Login
        http.apply(webAuthnLogin())
                .loginPage("/login")
                .usernameParameter("username")
                .passwordParameter("rawPassword");
    }
}
```

===== Integrating WebAuthnAuthenticationProvider

`WebAuthnAuthenticationProvider`, which is a `AuthenticationProvider` for Web Authentication, can also be configured with
JavaConfig. Please apply `WebAuthnAuthenticationProviderConfigurer` to a configuration class inherits
`WebSecurityConfigurerAdapter`.
To support multi-factor authentication with password and authenticator, `MultiFactorAuthenticationProvider` is what you
need, and `MultiFactorAuthenticationProviderConfigurer` configures it for you.

There are some points to be kept in mind when using `MultiFactorAuthenticationProvider`.
`AuthenticationProvider` to be delegated cannot to be registered to `AuthenticationManager`. If you delegate authentication
to `DaoAuthenticationProvider`, it is important not to use `DaoAuthenticationConfigurer` or
`AuthenticationManagerBuilder#userDetailsService`.

```java
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(AuthenticationManagerBuilder builder) throws Exception {
        builder.apply(new WebAuthnAuthenticationConfigurer<>(userDetailsService));
        builder.apply(new MultiFactorAuthenticationProviderConfigurer<>(daoAuthenticationProvider));
    }
}
```

==== User directory integration

Spring Security WebAuthn looks up a user through the `WebAuthnUserDetailsService` interface.
Please set a class implementing `WebAuthnUserDetailsService` to the `WebAuthnAuthenticationProvider` and the delegated
 `AuthenticationProvider`.

==== Validation on an authenticator registration

While it is basically application's responsibility to handle an authenticator registration process, Spring Security WebAuthn
provides converters and validators to examine the credential in question.
`Base64StringToCollectedClientDataConverter` converts Base64 string to a `CollectedClientData`.
`Base64StringToAttestationObjectConverter` converts Base64 string to a `AttestationObject`.

`WebAuthnRegistrationRequestValidator` validates an authenticator registration request.

==== Client interface specification

Web Authentication defines browser JavaScript APIs only. It is up to implementation the way to send corrected credential.
Regarding Spring Security WebAuthn, `WebAuthnProcessingFilter` retrieves `credentialId`, `clientData`, `authenticatorData`,
`signature`, `clientExtensionsJSON` for authentication, and `credentialId`, `clientData`, `authenticatorData` and
`signature` is binary data, please send them as Base64 strings.

==== Condition endpoint specification

Web Authentication requests to obtain a challenge from the server prior to authentication.
When using the FIDO-U2F token as an authentication device, the CredentialIds associated with the user identified by
the first authentication factor are also need to be obtained from the server.
To retrieve these data, Spring Security WebAuthn offers `ConditionEndpointFilter`.

=== Customization

==== Selecting authentication method

Spring Security WebAuthn supports "Password-less multi-factor authentication with a user-verifying authenticator",
"Multi-factor authentication with password and authenticator" and "Single-factor authentication like password".
If you put value on adoption, you may allow password authentication in your web system, or if you give greater importance
to security, you may restrict password authentication.


===== How to restrict password authentication

Restriction of single-factor authentication like password can be configured per user basis.
`MFAUserDetails` interface, which is a base interface of `WebAuthnUserDetails` has `isSingleFactorAuthenticationAllowed`
method. If an implementing class returns `true` by the method, the user can pass the authentication with only a single-factor
like password.
