== Introduction

=== Web Authentication

Web Authentication is a new, secure web application authentication specification standardizing under W3C.
By combining local authentication, public-key authentication, per-origin key management, it provides strong authentication to web sites against authentication process attacks like phishing.
Implementation is in progress in major browsers, the specification offers excellent choices for users who place importance on security and convenience.
Initially, the specification was developed as "FIDO 2.0: Web API for accessing FIDO 2.0 credentials" by the FIDO Alliance, but it has been transferred to W3C.

=== WebAuthn4J Spring Security

WebAuthn4J Spring Security is a Spring Security extension module to provide Web Authentication specification support for your Spring web application.

=== Requirements

==== Language & Framework

* Java8 or later
* Spring Framework 5.0 or later
* Spring Security 5.0 or later

==== Environment

* SecureContext
* Browsers
** Google Chrome 70 or later
** Mozilla Firefox 60 or later
** Microsoft Edge bundled with Windows 10 October 2018 Update or later
** Safari 14 or later

===== SecureContext

Web Authentication API is only available in SecureContext, which means only HTTPS connection is permitted while a user accessing web sites.
Browsers rejects Web Authentication API call if the web site is served through HTTP connection except `localhost`.
For more details about SecureContext, please see https://developer.mozilla.org/ja/docs/Web/Security/Secure_Contexts[MDN].

=== Source code

Source code for this project is hosted on https://github.com/webauthn4j/webauthn4j-spring-security[Github].

----
git clone https://github.com/webauthn4j/webauthn4j-spring-security
----

=== License

WebAuthn4J Spring Security is an open source software licensed under http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

=== Related Project

https://github.com/webauthn4j/webauthn4j[WebAuthn4J] is a portable Java library for WebAuthn assertion and attestation verification.
Spring Security is built on the top of it.

