name: Auto Merge

on: pull_request

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge
        run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
