[configuration]
== 設定

=== アプリケーションへの組み込み

==== Maven依存関係

[line-through]#ライブラリとその依存関係を導入するために、以下をpom.xmlファイルに追加してください。#
現在、まだカスタムビルドのSpring Securityを必要とする事情から、Maven Centralへの公開は行っていません。

[source, xml]
----
<dependency>
	<groupId>net.sharplab.springframework.security.extensions</groupId>
	<artifactId>spring-security-webauthn-core</artifactId>
	<version>${version}</version>
</dependency>
----

==== Java Config

===== WebAuthnProcessingFilterの組込

WebAuthnの認証要求を受け付ける `WebAuthnProcessingFilter` はJavaConfigで設定することが可能です。
`WebSecurityConfigurerAdapter` を継承したクラスで `protected void configure(HttpSecurity http)` メソッドをオーバーライドし、
`WebAuthnLoginConfigurer` を適用して下さい。 `WebAuthnLoginConfigurer` はインスタンスを返却する `webAuthnLogin` という
staticメソッドを持っていますので、そちらを活用すると良いでしょう。

```

import static net.sharplab.springframework.security.webauthn.config.configurers.WebAuthnLoginConfigurer.webAuthnLogin;

public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        // WebAuthn Login
        http.apply(webAuthnLogin())
                .loginPage("/login")
                .usernameParameter("username")
                .passwordParameter("rawPassword");
    }
}
```


=== 認証デバイス登録時の検証

認証デバイス登録操作のハンドリングは、基本的にはアプリケーション側の責務ですが、登録しようとしているデバイス情報が
認証時に使用できるものであるか検証する為に、Spring Security WebAuthnは `WebAuthnRegistrationRequestValidator` クラスを
提供します。

=== 認証時の検証

==== 認証方法の選択

Spring Security WebAuthnでは、認証方法として「ユーザー検証機能付き認証デバイスによるパスワードレス多要素認証」、
「パスワード＋認証デバイスによる多要素認証」、「パスワード等による単一要素認証」をサポートしています。
パスワード認証をサポートし、ユーザーへの間口を広げることも出来ますし、パスワード認証を制限することで、
セキュリティを高めることも出来ます。

===== パスワード認証を制限する方法

パスワード等による単一要素認証の許可・制限は、ユーザー単位で行うことが可能です。
`WebAuthnUserDetails` の基底インタフェースである `MFAUserDetails` インタフェースには、
`isSingleFactorAuthenticationAllowed` メソッドが存在し、実装クラスで `true` を返却すれば、そのユーザーは
パスワードなどの第一認証要素だけで認証をパスすることが出来ます。

=== ユーザーディレクトリとの統合



==== WebAuthnAuthenticatorServiceとWebAuthnAuthenticator

=== MultiFactorAuthenticationProvider

Spring Security WebAuthnは、多要素認証の実現に `MultiFactorAuthenticationProvider` を使用します。
`MultiFactorAuthenticationProvider` はSpring Securityで多要素認証を実現するための `AuthenticationProvider`
インタフェースの実装で、認証処理自体は別の `AuthenticationProvider` に委譲します。
委譲先の `AuthenticationProvider` での認証処理が成功し、単一要素認証が許可されていない場合、
`MultiFactorAuthenticationProvider`は委譲先の `AuthenticationProvider` の返却した `Authentication` の代わりに
`MultiFactorAuthenticationToken` を返却します。

`MultiFactorAuthenticationToken` は多要素認証における複数の認証要素の内、一部が完了し、一部が未完了であることを示す
`Authentication` インタフェースの実装です。デフォルトでは `AnonymousAuthenticationToken` と同様に、
認証が完了していないPrincipalとして扱われます。

Spring Security WebAuthnでパスワード＋認証デバイスによる多要素認証を実現するには、パスワード認証のための
`DaoAuthenticationProvider` を委譲先とした `MultiFactorAuthenticationProvider` を用意し、
`MultiFactorAuthenticationProvider` のみ `AuthenticationManager` にセットする必要があります。

なお、委譲先である `DaoAuthenticationProvider` は `AuthenticationManager` にセットしてはいけません。
これは、委譲先の `DaoAuthenticationProvider` が `MultiFactorAuthenticationProvider` を経由せずに `Authentication` を
処理してしまうと、 `MultiFactorAuthenticationToken` が返却されず、パスワードのみによる単一要素認証となってしまうためです。

=== WebAuthnAuthenticationProvider

`WebAuthnAuthenticationProvider` は `WebAuthnAssertionAuthenticationToken` を処理するための `AuthenticationProvider`
インタフェースの実装です。WebAuthnのアサーションの検証には `WebAuthnAuthenticationContextValidator` を使用します。
`WebAuthnAuthenticationContextValidator` については https://webauthn4j.github.io/webauthn4j/ja/[WebAuthn4Jのリファレンス] を参照して下さい。

=== 公開鍵の有効範囲（RpId）設定

Web Authentication仕様では、Credentialの作成時、即ち認証デバイスの登録時、そのCredentialの有効範囲を制限するための
パラメータとして、RpIdを指定します。RpIdには、～ドメインを指定することが出来ます。例えば、Credentialの作成を行った
ページのドメインが"subdomain.example.com"だった場合に、RpIdを"subdomain.example.com"と指定すれば、そのCredentialは
"subdomain.example.com"とそのサブドメインの範囲だけで利用できますが、RpIdを"example.com"とすることで、
公開鍵が利用可能な範囲を"example.com"およびそのサブドメインに広げることが出来ます。




== クライアントサイドとのインタフェース仕様

=== 認証リクエストに期待するリクエストパラメーター

=== メタデータエンドポイント仕様

=== 認証デバイスの登録

=== 認証

== 高度なトピック

=== 多要素認証で第一要素認証のみ完了したユーザーの識別

Spring Security本体側のトピック？

=== メタデータ

=== チャレンジ

==== ChallengeAttrProcessor

Web Authentication仕様では、署名対象データにChallengeを含める必要があります。spring-security-webauthn-thymeleafでは、
Challengeをサーバーから渡すために、Challengeデータを含むMetaタグを出力するThymeleafのCustom Dialectを提供します。

==== ChallengeRepository

Challengeデータの生成を管理を行うインタフェースとして、ChallengeRepositoryインタフェースが定義されています。

=== 証言ステートメント信頼性の検証

Relying Partyとして証言ステートメントを検証する際、署名と信頼のそれぞれの検証が必要です。
Spring-Security-WebAuthnはそれぞれ、`AttestationStatementSignatureValidator`インタフェースの実装および
`AttestationStatementTrustWorthinessValidator`インタフェースの実装を用いて検証を行います。

===== 信頼の検証

証言ステートメントを証明書パスに基づいて検証する際、spring-security-webauthnは
`WebAuthnTrustAnchorService`インタフェースの実装を用いてトラスト・アンカーを取得します。
信頼の検証は、証言ステートメントが自己署名か、ECDAAか、それ以外かによって方法が異なり、
spring-security-webauthnではそれぞれの検証手段のインタフェースとして`SelfAttestationTrustworthinessValidator`インタフェース、
`ECDAATrustworthinessValidator`インタフェース、`CertPathTrustworthinessValidator`インタフェースを用意しています。
`WebAuthnTrustAnchorService`インタフェースの実装クラスは必要とする検証の内容に応じて、
`StrictAttestationStatementTrustworthinessValidator`と`LooseAttestationStatementTrustworthinessValidator`を用意していますが、
実際の検証は`SelfAttestationTrustworthinessValidator`インタフェース、
 `ECDAATrustworthinessValidator`インタフェース、`CertPathTrustworthinessValidator`インタフェースを実装したクラスに
委譲しています。

`FIDOMetadataServiceCertPathTrustworthinessValidator`は`CertPathTrustworthinessValidator`インタフェースを実装したクラスで、
FIDO Metadata Serviceで公開されている証明書をトラストアンカーに証言証明書の信頼を検証します。
更に、FIDO Metadata Serviceから得られた各証言証明書のStatus Reportを元に検証を行います。

===== `FIDOMetadataServiceCertPathTrustworthinessValidator`



===== `KeyStoreResourceTrustAnchorProvider`

Java Key Storeファイルに保存した公開鍵証明書をトラストアンカーとして利用するための`TrustAnchorProvider`の
実装です。Springの `Resource` として読み込んだJava Key Storeファイルから `TrustAnchor` を提供します。


==== 証言ステートメント署名の検証

spring-security-webauthnは`AttestationStatementSignatureValidator`インタフェースの実装として、
`FIDOU2FAttestationStatementSignatureValidator`と`WebAuthnAttestationStatementSignatureValidator`を提供します。
spring-security-webauthnは`AttestationStatementSignatureValidator`インタフェースを実装したクラスのBeanを自動で検出し、
署名の検証時、フォーマットと適合する`AttestationStatementSignatureValidator`を使用して検証を行います。


