[configuration]
== 設定

=== アプリケーションへの組込

==== Maven依存関係

[line-through]#ライブラリとその依存関係を導入するために、以下をpom.xmlファイルに追加してください。#
現在、まだカスタムビルドのSpring Securityを必要とする事情から、Maven Centralへの公開は行っていません。

[source, xml]
----
<dependency>
	<groupId>net.sharplab.springframework.security.extensions</groupId>
	<artifactId>spring-security-webauthn-core</artifactId>
	<version>${version}</version>
</dependency>
----

==== Java Config

===== WebAuthnProcessingFilterの組込

WebAuthnの認証要求を受け付ける `WebAuthnProcessingFilter` はJavaConfigで設定することが可能です。
`WebSecurityConfigurerAdapter` を継承したクラスで `configure(HttpSecurity http)` メソッドをオーバーライドし、
`WebAuthnLoginConfigurer` を適用して下さい。 `WebAuthnLoginConfigurer` はインスタンスを返却する `webAuthnLogin()` という
staticメソッドを持っていますので、そちらを活用すると良いでしょう。

```

import static net.sharplab.springframework.security.webauthn.config.configurers.WebAuthnLoginConfigurer.webAuthnLogin;

public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        // WebAuthn Login
        http.apply(webAuthnLogin())
                .loginPage("/login")
                .usernameParameter("username")
                .passwordParameter("rawPassword");
    }
}
```

===== WebAuthnAuthenticationProviderの組込

Web Authentication用の `AuthenticationProvider` である `WebAuthnAuthenticationProvider` もJavaConfigで設定可能です。
`WebSecurityConfigurerAdapter` で `WebAuthnAuthenticationProviderConfigurer` を適用して下さい。
また、パスワード＋認証デバイスによる多要素認証をサポートする場合は、 `MultiFactorAuthenticationProvider` の設定が
必要ですが、こちらは `MultiFactorAuthenticationProviderConfigurer` を適用することで可能です。
`MultiFactorAuthenticationProvider` を使用する上での注意点として、 委譲先の `AuthenticationProvider` は
`AuthenticationManager` に登録してはならないというものがあります。 例えば、 `DaoAuthenticationProvider` に対して
委譲する場合、 `DaoAuthenticationProvider` を設定する `DaoAuthenticationConfigurer` や、
`AuthenticationManagerBuilder#userDetailsService` は使用しないで下さい。

```
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(AuthenticationManagerBuilder builder) throws Exception {
        builder.apply(new WebAuthnAuthenticationConfigurer<>(userDetailsService, authenticatorService));
        builder.apply(new MultiFactorAuthenticationProviderConfigurer<>(daoAuthenticationProvider));
    }
}
```

==== 認証デバイス登録時の検証

認証デバイス登録操作のハンドリングは、基本的にはアプリケーション側の責務ですが、登録しようとしているCredentialが
認証時に使用できるものであるか検証する為に、Spring Security WebAuthnはコンバータおよびバリデータを提供します。
`Base64StringToCollectedClientDataConverter` はBase64URL文字列を `CollectedClientData` に変換します。
`Base64StringToAttestationObjectConverter` はBase64URL文字列を `AttestationObject` に変換します。

`WebAuthnRegistrationRequestValidator` は、認証デバイスの登録要求の検証を行います。

==== クライアントサイドとのインタフェース仕様

WebAuthentication仕様では、ブラウザのJavaScript APIが規定されており、取得したCredentialをサーバーに対して送信する
インタフェースについては規定がありません。Spring Security WebAuthnでは、 `WebAuthnProcessingFilter` がログインURLに
対して送信されたリクエストからリクエストパラメータとして `credentialId` 、`clientData` 、 `authenticatorData` 、
`signature` 、`clientExtensionsJSON` を取得して認証を行います。 `credentialId` 、`clientData` 、 `authenticatorData` 、
`signature` はバイナリデータの為、Base64URLエンコードして送信して下さい。

===== コンディションエンドポイント仕様

WebAuthentication仕様では、認証に先立ってサーバーからチャレンジを取得する必要があります。
また、FIDO-U2Fトークンを認証デバイスとして使用する場合は、第一認証要素によって特定されたユーザーに紐づけられた
CredentialIdをサーバーから取得する必要があります。これらのデータを取得するためのエンドポイントとして、
Spring Security WebAuthnではコンディションエンドポイントを用意しています。

=== カスタマイズ

==== 認証方法の選択

Spring Security WebAuthnでは、認証方法として「ユーザー検証機能付き認証デバイスによるパスワードレス多要素認証」、
「パスワード＋認証デバイスによる多要素認証」、「パスワード等による単一要素認証」をサポートしています。
パスワード認証をサポートし、ユーザーへの間口を広げることも出来ますし、パスワード認証を制限することで、
セキュリティを高めることも出来ます。

===== パスワード認証を制限する方法

パスワード等による単一要素認証の許可・制限は、ユーザー単位で行うことが可能です。`WebAuthnUserDetails` の
基底インタフェースである `MFAUserDetails` インタフェースには、`isSingleFactorAuthenticationAllowed` メソッドが存在し、
実装クラスで `true` を返却すれば、そのユーザーはパスワードなどの第一認証要素だけで認証をパスすることが出来ます。

===== MultiFactorAuthenticationProvider

Spring Security WebAuthnは、多要素認証の実現に `MultiFactorAuthenticationProvider` を使用します。
`MultiFactorAuthenticationProvider` はSpring Securityで多要素認証を実現するための `AuthenticationProvider`
インタフェースの実装で、認証処理自体は別の `AuthenticationProvider` に委譲します。
委譲先の `AuthenticationProvider` での認証処理が成功し、単一要素認証が許可されていない場合、
`MultiFactorAuthenticationProvider` は委譲先の `AuthenticationProvider` の返却した `Authentication` の代わりに
`MultiFactorAuthenticationToken` を返却します。

`MultiFactorAuthenticationToken` は多要素認証における複数の認証要素の内、一部が完了し、一部が未完了であることを示す
`Authentication` インタフェースの実装です。デフォルトでは `AnonymousAuthenticationToken` と同様に、
認証が完了していないPrincipalとして扱われます。

Spring Security WebAuthnでパスワード＋認証デバイスによる多要素認証を実現するには、パスワード認証のための
`DaoAuthenticationProvider` を委譲先とした `MultiFactorAuthenticationProvider` を用意し、
`MultiFactorAuthenticationProvider` のみ `AuthenticationManager` にセットする必要があります。
委譲先である `DaoAuthenticationProvider` は `AuthenticationManager` にセットしてはいけません。
これは、委譲先の `DaoAuthenticationProvider` が `MultiFactorAuthenticationProvider` を経由せずに `Authentication` を
処理してしまうと、 `MultiFactorAuthenticationToken` が返却されず、パスワードのみによる単一要素認証となってしまうためです。

===== WebAuthnAuthenticationProvider

`WebAuthnAuthenticationProvider` は `WebAuthnAssertionAuthenticationToken` を処理するための `AuthenticationProvider`
インタフェースの実装です。WebAuthnのアサーションの検証には `WebAuthnAuthenticationContextValidator` を使用します。
`WebAuthnAuthenticationContextValidator` については https://webauthn4j.github.io/webauthn4j/ja/[WebAuthn4Jのリファレンス] を参照して下さい。

==== ユーザーディレクトリとの統合

===== WebAuthnUserDetailsService


===== 公開鍵の有効範囲（RpId）設定

Web Authentication仕様では、Credentialの作成時、即ち認証デバイスの登録時、そのCredentialの有効範囲を制限するための
パラメータとして、RpIdを指定します。RpIdには、～ドメインを指定することが出来ます。例えば、Credentialの作成を行った
ページのドメインが"subdomain.example.com"だった場合に、RpIdを"subdomain.example.com"と指定すれば、そのCredentialは
"subdomain.example.com"とそのサブドメインの範囲だけで利用できますが、RpIdを"example.com"とすることで、
公開鍵が利用可能な範囲を"example.com"およびそのサブドメインに広げることが出来ます。


=== 高度なトピック

==== 多要素認証で第一要素のみ認証完了したユーザーの識別

多要素認証で第一要素のみ認証完了しているかどうかで、ログインページの表示を変更したい場合、以下のように
現在の `Authentication` インスタンスが `MultiFactorAuthenticationToken` か否かで判断することが出来ます。

```java
@RequestMapping(value = "/login", method = RequestMethod.GET)
public String login() {
    Authentication authentication =
            SecurityContextHolder.getContext().getAuthentication();
    if (authentication instanceof MultiFactorAuthenticationToken) {
        return ViewNames.VIEW_LOGIN_AUTHENTICATOR_LOGIN;
    } else {
        return ViewNames.VIEW_LOGIN_LOGIN;
    }
}
```

==== 構成証明ステートメントの検証

Web Authentication仕様では、認証デバイスの登録時に要求すれば認証デバイスの構成証明ステートメントを取得することが出来ます。
Relying Partyは取得した構成証明ステートメントを検証することで、セキュリティ要件に合致しない認証デバイスを除外する
ことが可能です。
但し、構成証明ステートメントにはユーザーのサイトを跨いだトラッキングに利用できる情報が含まれていることから、
構成証明ステートメントを要求した場合、ブラウザはユーザーに対して追加のダイアログを表示するため、ユーザビリティが
低下します。認証デバイスの厳密な検証が必要なエンタープライズ用途以外、通常のB2Cサイトでは、構成証明ステートメントの
要求を行うべきではないでしょう。

WebAuthn4Jでは、`WebAuthnRegistrationContextValidator` が認証デバイスの登録要求の検証を司りますが、
取得した構成証明ステートメントの署名と信頼性の検証は、それぞれ`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

厳密な構成証明ステートメントの検証を必要としないサイト向けに、`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した`WebAuthnRegistrationContextValidator` のインスタンスは、
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドで作成出来ます。

===== KeyStoreResourceTrustAnchorProvider

Java Key Storeファイルに保存した公開鍵証明書をトラストアンカーとして利用するための`TrustAnchorProvider`の
実装です。Springの `Resource` として読み込んだJava Key Storeファイルから `TrustAnchor` を提供します。




