
== 設定

=== アプリケーションへの組込

==== Maven依存関係

[line-through]#ライブラリとその依存関係を導入するために、以下をpom.xmlファイルに追加してください。#

現在、まだMaven Centralへの公開は行っていません。

[source,xml]
----
<properties>
  ...
  <!-- Use the latest version whenever possible. -->
  <webauthn4j-spring-security.version>0.7.0.RELEASE</webauthn4j-spring-security.version>
  ...
</properties>

<dependency>
	<groupId>com.webauthn4j</groupId>
	<artifactId>webauthn4j-spring-security-core</artifactId>
	<version>${webauthn4j-spring-security.version}</version>
</dependency>
----

==== Java Config

WebAuthn4J Spring Securityは、Security SecurityのJava Configで設定することが可能です。
WebAuthnの認証リクエストを受け付ける `WebAuthnProcessingFilter` や、 WebAuthn JS APIのリクエストパラメータを返却するAttestation Optionsエンドポイント、Assertion Optionsエンドポイントを構成することが可能です。

`WebSecurityConfigurerAdapter` を継承したクラスで `configure(HttpSecurity http)` メソッドをオーバーライドし、
`WebAuthnLoginConfigurer` を適用して下さい。 `WebAuthnLoginConfigurer` はインスタンスを返却する `webAuthnLogin()` という staticメソッドを持っていますので、そちらを活用すると良いでしょう。

[source,java]
----

import static WebAuthnLoginConfigurer.webAuthnLogin;

public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        // WebAuthn Login
        http.apply(webAuthnLogin())
                .loginPage("/login")
                .usernameParameter("username")
                .passwordParameter("rawPassword");
    }
}
----

===== WebAuthnAuthenticationProviderの組込

Web Authentication用の `AuthenticationProvider` である `WebAuthnAuthenticationProvider` もJavaConfigで設定可能です。
`WebSecurityConfigurerAdapter` を継承したクラスで `configure(AuthenticationManagerBuilder builder)` メソッドをオーバーライドし、
`WebAuthnAuthenticationProviderConfigurer` を適用して下さい。

[source,java]
----
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(AuthenticationManagerBuilder builder) throws Exception {
        builder.apply(new WebAuthnAuthenticationProviderConfigurer<>(authenticatorService, webAuthnManager));
    }
}
----

==== 永続化層との統合

WebAuthn4J Spring Securityは `WebAuthnAuthenticatorService` インタフェースを通じて認証デバイスを検索します。
`WebAuthnAuthenticatorService` を実装したクラスを用意し、 `WebAuthnAuthenticationProvider` にセットして下さい。
JavaConfigの場合、`WebAuthnAuthenticationProviderConfigurer` のコンストラクタを通じてセット出来ます。

=== クライアントサイドとのインタフェース仕様

Web Authentication仕様では、ブラウザのJavaScript APIが規定されており、取得した資格情報をサーバーに対して送信する インタフェースについては規定がありません。

==== WebAuthn認証リクエストの処理

WebAuthn4J Spring Securityでは、認証処理に関しては、ログインURLに対して送信されたリクエストから `WebAuthnProcessingFilter` がリクエストパラメータとして
`credentialId` 、`clientData` 、 `authenticatorData` 、`signature` 、`clientExtensionsJSON` を取得して認証を行います。
`credentialId` 、`clientData` 、 `authenticatorData` 、`signature` はバイナリデータの為、クライアントサイドはBase64URLエンコードして送信して下さい。

==== 認証デバイス登録時の処理

認証処理と異なり、登録処理については、通常WebAuthn以外のデータ、例えばユーザーの氏名やメールアドレスなども一緒に登録する必要があることから、
WebAuthn4J Security Securityとして一律のエンドポイントを設けることは難しく、登録処理用のServlet Filterの提供は行っていません。
認証デバイス登録操作のハンドリングは、基本的にはアプリケーション側の責務ですが、登録しようとしている資格情報が
認証時に使用できるものであるか検証する為に、WebAuthn4J Spring Securityはコンバータおよびバリデータを提供します。
`Base64StringToCollectedClientDataConverter` はBase64URL文字列を `CollectedClientData` に変換します。
`Base64StringToAttestationObjectConverter` はBase64URL文字列を `AttestationObject` に変換します。
`WebAuthnRegistrationRequestValidator` は、認証デバイスの登録リクエストの検証に用いることが出来ます。

===== オプションエンドポイント

Web Authentication仕様では、WebAuthn JS APIで資格情報の作成、認証を行う際にAPIの引数としてサーバーから取得したチャレンジ渡す必要があります。
また、FIDO-U2Fトークンを認証デバイスとして使用する場合も、第一認証要素によって特定されたユーザーに紐づけられた CredentialIdをサーバーから取得して渡す必要があります。
これらのWebAuthn JS APIの引数をサーバーから取得するためのエンドポイントとして、 WebAuthn4J Spring Securityでは `AttestationOptionsEndpointFilter` と `AssertionOptionsEndpointFilter` を用意しています。

=== カスタマイズ

==== WebAuthnProcessingFilter

`WebAuthnProcessingFilter` は、受信したリクエストから `credentialId` 、`clientData` 、 `authenticatorData` 、`signature` 、`clientExtensionsJSON`
といったパラメータを取得して `WebAuthnAssertionAuthenticationToken` の組立を行います。
`credentialId` パラメータが受信したリクエストに存在しない場合は、 `username` 、 `password` パラメータを読み取り、
`UsernamePasswordAuthenticationToken` を組み立てます。 リクエストパラメータ名を変更したい場合は、
`WebAuthnProcessingFilter` のプロパティ、あるいは `WebAuthnLoginConfigurer` の対応するJava Configメソッドから設定可能です。

==== WebAuthnAuthenticationProvider

`WebAuthnAuthenticationProvider` は `WebAuthnAssertionAuthenticationToken` を処理するための `AuthenticationProvider`
インタフェースの実装です。WebAuthnのアサーションの検証には `WebAuthnManager` を使用します。
`WebAuthnManager` については https://webauthn4j.github.io/webauthn4j/ja/[WebAuthn4Jのリファレンス] を参照して下さい。

==== Attestation Optionsエンドポイント、Assertion optionsエンドポイント

WebAuthn4J Spring Securityは、WebAuthn JS APIで資格情報の作成を行う際のパラメータを返却するエンドポイントとして `AttestationOptionsEndpointFilter` を、
認証を行う際のパラメータを返却する際のエンドポイントとして `AssertionOptionsEndpointFilter` を用意しています。
返却する値の生成は、それぞれ `AttestationOptionsProvider` インタフェース、 `AssertionOptionsProvider` インタフェースを通じて委譲されているので、
これらのカスタム実装を行うことで、返却値を自由にカスタマイズすることが可能です。

Java Configからカスタマイズも可能です。 `WebAuthnLoginConfigurer` の `attestationOptionsEndpoint` メソッドあるいは `assertionOptionsEndpoint` からのチェーンを用いて
カスタマイズすることが出来ます。

[source,java]
----
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
       @Override
        protected void configure(HttpSecurity http) throws Exception {

            http.apply(WebAuthnLoginConfigurer.webAuthnLogin())
                    .attestationOptionsEndpoint()
                        .attestationOptionsProvider(attestationOptionsProvider)
                        .processingUrl("/webauthn/attestation/options")
                        .rp()
                            .id("example.com")
                            .icon("dummy")
                            .name("example")
                            .and()
                        .pubKeyCredParams(
                                new PublicKeyCredentialParameters(PublicKeyCredentialType.PUBLIC_KEY, COSEAlgorithmIdentifier.ES256),
                                new PublicKeyCredentialParameters(PublicKeyCredentialType.PUBLIC_KEY, COSEAlgorithmIdentifier.RS1)
                        )
                        .timeout(10000L)
                        .authenticatorSelection()
                            .authenticatorAttachment(AuthenticatorAttachment.CROSS_PLATFORM)
                            .residentKey(ResidentKeyRequirement.PREFERRED)
                            .userVerification(UserVerificationRequirement.PREFERRED)
                            .and()
                        .attestation(AttestationConveyancePreference.DIRECT)
                        .extensions()
                            .credProps(true)
                            .uvm(true)
                            .entry("unknown", true)
                            .extensionProviders((builder, httpServletRequest) -> builder.set("extensionProvider", httpServletRequest.getRequestURI()))
                        .and()
                    .assertionOptionsEndpoint()
                        .assertionOptionsProvider(assertionOptionsProvider)
                        .processingUrl("/webauthn/assertion/options")
                        .rpId("example.com")
                        .timeout(20000L)
                        .userVerification(UserVerificationRequirement.PREFERRED)
                        .extensions()
                            .appid("appid")
                            .appidExclude("appidExclude")
                            .uvm(true)
                            .entry("unknown", true)
                            .extensionProviders((builder, httpServletRequest) -> {
                                builder.set("extensionProvider", httpServletRequest.getRequestURI());
                            })
                        .and()
                    .and();
        }
}
----

===== PublicKeyCredentialUserEntityの動的な生成

Attestation Optionsエンドポイントは、返却する `PublicKeyCredentialUserEntity` をログイン中のユーザーの `Authentication` に基づいて
動的に生成することが可能です。動的に生成する為のハンドラとして `PublicKeyCredentialUserEntityProvider` インタフェースが用意されています。
`AttestationOptionsProviderImpl` クラスの `setPublicKeyCredentialUserEntityProvider` メソッドからセットしてください。

Java Configの場合は、以下のようにセット可能です。

----
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
       @Override
        protected void configure(HttpSecurity http) throws Exception {

            http.apply(WebAuthnLoginConfigurer.webAuthnLogin())
                    .attestationOptionsEndpoint()
                        .attestationOptionsProvider(attestationOptionsProvider)
                        .processingUrl("/webauthn/attestation/options")
                        .user(new MyPublicKeyCredentialUserEntityProvider()) // put your PublicKeyCredentialUserEntityProvider implementation
        }
}
----

WebAuthn4J Spring SecurityのJava Configは、明示的に指定されていない場合、SpringのApplicationContextから `PublicKeyCredentialUserEntityProvider` を検索しますので、
Bean登録することでも `PublicKeyCredentialUserEntityProvider` のセットが可能です。

==== 認証方法の選択

WebAuthn4J Spring Securityでは、認証方法として「ユーザー検証機能付き認証デバイスによるパスワードレス多要素認証」、 「パスワード＋認証デバイスによる多要素認証」、「パスワード等による単一要素認証」をサポートしています。
パスワード認証をサポートし、ユーザーへの間口を広げることも出来ますし、パスワード認証を制限することで、 セキュリティを高めることも出来ます。

===== パスワード認証の実装

「パスワード＋認証デバイスによる多要素認証」、「パスワード等による単一要素認証」をサポートする場合、 `WebAuthnAuthenticationProvider` に加えて、 `DaoAuthenticationProvider` を構成し、 `UsernamePasswordAuthenticationToken` を処理できるようにする必要があります。
「パスワード＋認証デバイスによる多要素認証」が必要なページは、WebAuthnで認証されているかを認可要件に含めることで実装出来ます。

WebAuthnで認証されているかは、 `WebAuthnSecurityExpression#isWebAuthnAuthenticated` メソッドでチェック可能です。WebAuthnSecurityExpressionのインスタンスをBean登録し、JavaConfigから呼び出してください。
WebAuthn4J Spring Security Sample MPA で実装例を示しているので、参考にして下さい。

=== 高度なトピック

==== 多要素認証で第一要素のみ認証完了したユーザーの識別

ユーザーの認証レベルによって異なるページを表示したい場合、以下のように現在の `Authentication` インスタンスの型で画面を切り替えるのが一つの方法です。

[source,java]
----
@RequestMapping(value = "/login", method = RequestMethod.GET)
public String login() {
    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
    if (authenticationTrustResolver.isAnonymous(authentication)) {
        return VIEW_LOGIN_LOGIN;
    } else {
        return VIEW_LOGIN_AUTHENTICATOR_LOGIN;
    }
}
----

==== 資格情報の有効範囲（RpId）設定

Web Authentication仕様では、資格情報の作成時、即ち認証デバイスの登録時、その資格情報の有効範囲を制限するための パラメータとして、 `rpId` を指定します。
`rpId` には、 https://html.spec.whatwg.org/multipage/origin.html#concept-origin-effective-domain[effective domain] を指定することが出来ます。
例えば、資格情報の作成を行った ページのドメインが `dev.example.com` だった場合に、RpIdを `dev.example.com` と指定すれば、その資格情報は `dev.example.com` とそのサブドメインの範囲だけで利用できますが、 `rpId` を `example.com` とすることで、 資格情報が利用可能な範囲を `example.com` およびそのサブドメインに広げることが出来ます。

WebAuthn4J Spring Securityでは、 `rpId` は `ServerPropertyProviderImpl` のプロパティとして設定可能で、JavaConfigでは、 `WebAuthnConfigurer` を通じて設定可能です。
リクエストに応じて動的に変更したい場合、`RpIdProvider`をセットしてください。

==== 構成証明ステートメントの検証

Web Authentication仕様では、認証デバイスの登録時に要求すれば認証デバイスの構成証明ステートメントを取得することが出来ます。
Relying Partyは取得した構成証明ステートメントを検証することで、セキュリティ要件に合致しない認証デバイスの受け入れを拒否することが可能です。
但し、構成証明ステートメントにはユーザーのサイトを跨いだトラッキングに利用できる情報が含まれていることから、無闇に 要求するべきではありません。また、構成証明ステートメントを要求した場合、ブラウザはユーザーに対して追加のダイアログを 表示するため、ユーザビリティが低下することも注意が必要です。認証デバイスの厳密な検証が必要なエンタープライズ用途以外、 通常のB2Cサイトでは、構成証明ステートメントの要求を行うべきではないでしょう。

WebAuthn4Jでは、`WebAuthnRegistrationContextValidator` が認証デバイスの登録リクエストの検証を行いますが、 取得した構成証明ステートメントの署名と信頼性の検証は、それぞれ `AttestationStatementValidator` と
`CertPathTrustworthinessValidator` インタフェースの実装に委譲します。

厳密な構成証明ステートメントの検証を必要としないサイト向けに、`AttestationStatementValidator` と
`CertPathTrustworthinessValidator` を構成した `WebAuthnRegistrationContextValidator` のインスタンスは、
`WebAuthnRegistrationContextValidator.createNonStrictRegistrationContextValidator` ファクトリメソッドで作成出来ます。

==== SpringのResourceを活用したTrustAnchorProvider

認証デバイスを登録時に証明書パスから検証する場合、 `TrustAnchorCertPathTrustworthinessValidator` クラスは
`TrustAnchorProvider` インタフェースの実装クラスから取得した `TrustAnchor` を使用します。WebAuthn4J Spring Securityでは、 SpringのResourceとして読み込んだJava Key Storeファイルを `TrustAnchor` として使用する `TrustAnchorProvider` として、
`KeyStoreResourceTrustAnchorProvider` クラスを提供します。

