== 導入

=== Web Authenticationとは

Web Authenticationは、W3Cで仕様策定が進められている、Webアプリケーションの新しいセキュアな認証方式仕様です。 ローカル認証や公開鍵認証、Origin別の鍵管理を組み合わせることで、フィッシングなど認証プロセスに対する攻撃に対して堅固な認証を実現しています。 主要ブラウザでの実装が進みつつあり、セキュリティ、利便性を重視するユーザーに対して優れた選択肢を提供します。 当初はFIDO AllianceでFIDO 2.0: Web API for accessing FIDO 2.0 credentialsとして仕様策定が進められていましたが、 現在はW3Cに移管され、仕様策定が行われています。

=== WebAuthn4J Spring Securityとは

Spring Securityで保護されたWebアプリケーションに対して、Web Authentication仕様に基づく認証機能を提供するための Spring Security拡張です。

=== 要件

==== 言語・フレームワーク

* Java8以降
* Spring Framework 5.0以降
* Spring Security 5.0以降

==== 動作環境

WebAuthn4J Spring Securityの動作環境は、以下の要件を満たす必要があります。

* SecureContext
* ブラウザ
** Google Chrome 70以降
** Mozilla Firefox 60以降
** Microsoft Edge Windows 10 October 2018 Update同梱版 以降
** Safari 14以降

===== SecureContext

Web Authentication仕様では、動作環境がSecureContextであることを要求しています。 これは、ユーザーがサイトに接続する際、HTTPS接続でなければならないことを意味します。HTTP接続環境下では、ブラウザはWebAuthnに関連した要求を拒否するため、利用できません。 但し、 `localhost` では例外的にHTTP接続が認められています。SecureContextについて詳しくは https://developer.mozilla.org/ja/docs/Web/Security/Secure_Contexts[MDN] を参照ください。

=== ソースコード

ソースコードは https://github.com/webauthn4j/webauthn4j-spring-security[Github] で管理されています。

[source,bash]
----
git clone https://github.com/webauthn4j/webauthn4j-spring-security
----

=== ライセンス

WebAuthn4J Spring Securityは http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license] ライセンスの オープンソースソフトウェアです。

=== 関連プロジェクト

WebAuthnのアサーションの検証に関わるコアの処理は https://github.com/webauthn4j/webauthn4j[WebAuthn4J] という別のプロジェクトで開発を進めています。
